-- -----------------------------------------------------
-- Table pokemons
-- -----------------------------------------------------
DROP TABLE IF EXISTS pokemons;
CREATE TABLE IF NOT EXISTS pokemons (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `pokedex_number` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `type1` VARCHAR(20) NOT NULL,
  `type2` VARCHAR(20),
  `hp` INT NOT NULL,
  `attack` INT NOT NULL,
  `defense` INT NOT NULL,
  `special_attack` INT NOT NULL,
  `special_defense` INT NOT NULL,
  `speed` INT NOT NULL,
  `image_url` VARCHAR(255),
  `description` TEXT -- Ajout de la colonne description
);

DROP TABLE IF EXISTS team;
CREATE TABLE IF NOT EXISTS team (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `pokedex_number` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `type1` VARCHAR(20) NOT NULL,
  `type2` VARCHAR(20),
  `hp` INT NOT NULL,
  `attack` INT NOT NULL,
  `defense` INT NOT NULL,
  `special_attack` INT NOT NULL,
  `special_defense` INT NOT NULL,
  `speed` INT NOT NULL,
  `image_url` VARCHAR(255),
  `level` INT NOT NULL DEFAULT 1,
  `description` TEXT 
);

-- Suppression des anciens enregistrements
DELETE FROM pokemons;
DELETE FROM sqlite_sequence WHERE name='pokemons';

DELETE FROM team;
DELETE FROM sqlite_sequence WHERE name='team';


-- Insertion des Pokémon avec description
INSERT INTO pokemons (`pokedex_number`, `name`, `type1`, `type2`, `hp`, `attack`, `defense`, `special_attack`, `special_defense`, `speed`, `image_url`, `description`) VALUES
(1, 'Bulbizarre', 'Plante', 'Poison', 45, 49, 49, 65, 65, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 'Un Pokémon Plante et Poison avec une graine sur son dos.'),
(2, 'Herbizarre', 'Plante', 'Poison', 60, 62, 63, 80, 80, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 'Évolution de Bulbizarre, sa fleur commence à éclore.'),
(3, 'Florizarre', 'Plante', 'Poison', 80, 82, 83, 100, 100, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 'L’évolution finale de Bulbizarre, Florizarre est doté d’une grande fleur sur son dos.'),
(4, 'Salamèche', 'Feu', NULL, 39, 52, 43, 60, 50, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 'Un petit Pokémon de feu avec une flamme au bout de sa queue.'),
(5, 'Reptincel', 'Feu', NULL, 58, 64, 58, 80, 65, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 'Évolution de Salamèche, Reptincel est plus grand et plus puissant.'),
(6, 'Dracaufeu', 'Feu', 'Vol', 78, 84, 78, 109, 85, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 'L’évolution finale de Salamèche, Dracaufeu crache des flammes brûlantes.'),
(7, 'Carapuce', 'Eau', NULL, 44, 48, 65, 50, 64, 43, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 'Un Pokémon Eau avec une carapace protectrice.'),
(8, 'Carabaffe', 'Eau', NULL, 59, 63, 80, 65, 80, 58, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 'Évolution de Carapuce, il utilise sa carapace pour se protéger et attaquer.'),
(9, 'Tortank', 'Eau', NULL, 79, 83, 100, 85, 105, 78, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 'L’évolution finale de Carapuce, il possède des canons sur son dos pour tirer de puissants jets d’eau.'),
(10, 'Chenipan', 'Insecte', NULL, 45, 30, 35, 20, 20, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', 'Un Pokémon Insecte qui rampe lentement et mange des feuilles.'),
(11, 'Chrysacier', 'Insecte', NULL, 50, 20, 55, 25, 25, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png', 'Une larve qui se transforme lentement en papillon.'),
(12, 'Papilusion', 'Insecte', 'Vol', 60, 45, 50, 90, 80, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png', 'Papilusion vole avec grâce grâce à ses grandes ailes colorées.'),
(13, 'Aspicot', 'Insecte', 'Poison', 40, 35, 30, 20, 20, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png', 'Un petit Pokémon Insecte qui peut infliger un poison à ses ennemis.'),
(14, 'Coconfort', 'Insecte', 'Poison', 45, 25, 50, 25, 25, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png', 'Il se transforme en papillon dans sa chrysalide.'),
(15, 'Dardargnan', 'Insecte', 'Poison', 65, 90, 40, 45, 80, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png', 'Un Pokémon Insecte agressif qui défend son territoire avec des piqûres.'),
(16, 'Roucool', 'Normal', 'Vol', 40, 45, 40, 35, 35, 56, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', 'Un Pokémon oiseau qui aime voler et chanter dans le ciel.'),
(17, 'Roucoups', 'Normal', 'Vol', 63, 60, 55, 50, 50, 71, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png', 'Un Pokémon oiseau robuste, il est un bon compagnon de vol.'),
(18, 'Roucarnage', 'Normal', 'Vol', 83, 80, 75, 70, 70, 101, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png', 'Un Pokémon de vol puissant qui attaque avec ses griffes acérées.'),
(19, 'Rattata', 'Normal', NULL, 30, 56, 35, 25, 35, 72, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png', 'Un petit Pokémon rongeur qui adore fouiller les poubelles.'),
(20, 'Rattatac', 'Normal', NULL, 55, 81, 60, 50, 70, 97, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png', 'Il est plus grand et plus fort que Rattata, avec des dents acérées.'),
(21, 'Piafabec', 'Normal', 'Vol', 40, 60, 30, 31, 31, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png', 'Un Pokémon au long bec qui aime manger des insectes.'),
(22, 'Rapasdepic', 'Normal', 'Vol', 65, 90, 65, 61, 61, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png', 'Un Pokémon de vol rapide qui attaque avec ses griffes.'),
(23, 'Abo', 'Poison', NULL, 35, 60, 44, 40, 54, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png', 'Un serpent qui se faufile dans l’herbe à la recherche de proies.'),
(24, 'Arbok', 'Poison', NULL, 60, 85, 69, 65, 79, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png', 'Il se dresse pour intimider ses ennemis avec son grand corps.'),
(25, 'Pikachu', 'Electrik', NULL, 35, 55, 40, 50, 50, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'Un petit Pokémon qui génère de l’électricité avec ses joues.'),
(26, 'Raichu', 'Electrik', NULL, 60, 90, 55, 90, 80, 110, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png', 'L’évolution de Pikachu, Raichu est rapide et puissant.'),
(27, 'Sabelette', 'Sol', NULL, 50, 75, 85, 20, 30, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png', 'Un Pokémon qui creuse sous terre à la recherche de nourriture.'),
(28, 'Sablaireau', 'Sol', NULL, 75, 100, 110, 45, 55, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png', 'L’évolution de Sabelette, il peut creuser de profonds tunnels.'),
(29, 'Nidoran♀', 'Poison', NULL, 55, 47, 52, 40, 40, 41, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png', 'Un petit Pokémon qui défend son territoire avec des piqûres.'),
(30, 'Nidorina', 'Poison', NULL, 70, 62, 67, 55, 55, 56, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png', 'L’évolution de Nidoran♀, elle devient plus forte et plus résistante.'),
(31, 'Nidoqueen', 'Poison', 'Sol', 90, 92, 87, 75, 85, 76, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png', 'Une Pokémon puissant et protecteur, elle est redoutable en combat.'),
(32, 'Nidoran♂', 'Poison', NULL, 46, 57, 40, 40, 40, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png', 'Un petit Pokémon qui montre son côté agressif lorsqu’il se sent menacé.'),
(33, 'Nidorino', 'Poison', NULL, 61, 72, 57, 55, 55, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png', 'L’évolution de Nidoran♂, il devient plus confiant et combatif.'),
(34, 'Nidoking', 'Poison', 'Sol', 81, 102, 77, 85, 75, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png', 'Un Pokémon imposant, il est redouté pour sa force brute.'),
(35, 'Mélofée', 'Fée', NULL, 70, 45, 48, 60, 65, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png', 'Un Pokémon mignon qui chante des chansons douces pour charmer ses amis.'),
(36, 'Mélodelfe', 'Fée', NULL, 95, 70, 73, 95, 90, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png', 'Une version plus forte de Mélofée, elle utilise sa magie pour aider les autres.'),
(37, 'Goupix', 'Feu', NULL, 38, 41, 40, 50, 65, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png', 'Un petit Pokémon de feu qui protège sa queue enflammée.'),
(38, 'Feunard', 'Feu', NULL, 73, 76, 75, 81, 100, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png', 'L’évolution de Goupix, il est connu pour sa beauté et sa sagesse.'),
(39, 'Rondoudou', 'Normal', 'Fée', 115, 45, 20, 45, 25, 20, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png', 'Un Pokémon mignon qui endort ses ennemis avec ses chants.'),
(40, 'Grodoudou', 'Normal', 'Fée', 140, 70, 45, 85, 50, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png', 'L’évolution de Rondoudou, elle est encore plus puissante et charmante.'),
(41, 'Nosferapti', 'Poison', 'Vol', 40, 45, 35, 30, 40, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png', 'Un petit Pokémon chauve-souris qui vole la nuit à la recherche de fruits.'),
(42, 'Nosferalto', 'Poison', 'Vol', 75, 80, 70, 65, 75, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png', 'L’évolution de Nosferapti, plus puissant et plus agile.'),
(43, 'Mystherbe', 'Plante', 'Poison', 45, 50, 55, 75, 65, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png', 'Un Pokémon plante qui utilise le poison pour se défendre.'),
(44, 'Ortide', 'Plante', 'Poison', 60, 65, 70, 85, 75, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png', 'Une plante qui pousse dans des zones humides et utilise le poison pour chasser.'),
(45, 'Rafflesia', 'Plante', 'Poison', 75, 80, 85, 110, 90, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png', 'Une plante fleurie qui dégage une odeur puissante pour attirer ses proies.'),
(46, 'Paras', 'Insecte', 'Plante', 35, 70, 55, 45, 55, 25, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png', 'Un Pokémon qui a des champignons sur son dos, il se nourrit de nutriments.'),
(47, 'Parasect', 'Insecte', 'Plante', 60, 95, 80, 60, 80, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png', 'Une version plus grande de Paras, ses champignons prennent le contrôle de son corps.'),
(48, 'Mimitoss', 'Insecte', 'Poison', 60, 55, 50, 40, 55, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png', 'Un Pokémon qui adore se cacher sous les feuilles.'),
(49, 'Aéromite', 'Insecte', 'Poison', 70, 65, 60, 90, 75, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png', 'Un Pokémon Insecte capable de voler rapidement avec ses ailes.'),
(50, 'Taupiqueur', 'Sol', NULL, 10, 55, 25, 35, 45, 95, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png', 'Un petit Pokémon qui creuse à la recherche de terre et de minéraux.'),
(51, 'Triopikeur', 'Sol', NULL, 35, 100, 50, 50, 70, 120, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png', 'Une version plus forte de Taupiqueur, il est très rapide dans le sol.'),
(52, 'Miaouss', 'Normal', NULL, 40, 45, 35, 40, 40, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png', 'Un Pokémon chat qui aime chasser et chercher des trésors.'),
(53, 'Persian', 'Normal', NULL, 65, 70, 60, 65, 65, 115, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png', 'L’évolution de Miaouss, il est rapide et élégant.'),
(54, 'Psykokwak', 'Eau', NULL, 50, 52, 48, 65, 50, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png', 'Un Pokémon qui souffre souvent de maux de tête, mais qui utilise l’eau avec magie.'),
(55, 'Akwakwak', 'Eau', NULL, 80, 82, 78, 95, 80, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png', 'L’évolution de Psykokwak, il utilise des pouvoirs psychiques puissants.'),
(56, 'Férosinge', 'Combat', NULL, 40, 80, 35, 35, 45, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png', 'Un petit Pokémon de combat avec une forte personnalité.'),
(57, 'Colossinge', 'Combat', NULL, 65, 105, 60, 60, 70, 95, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png', 'L’évolution de Férosinge, il est puissant et redoutable.'),
(58, 'Caninos', 'Feu', NULL, 55, 70, 45, 70, 50, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png', 'Un Pokémon loup de feu, il est loyal et protecteur.'),
(59, 'Arcanin', 'Feu', NULL, 90, 110, 80, 100, 80, 95, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png', 'L’évolution de Caninos, connu pour sa vitesse incroyable.'),
(60, 'Ptitard', 'Eau', NULL, 40, 50, 40, 40, 40, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png', 'Un petit Pokémon qui nage et joue dans l’eau.'),
(61, 'Têtarte', 'Eau', NULL, 65, 65, 65, 50, 50, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png', 'L’évolution de Ptitard, il grandit et devient plus fort.'),
(62, 'Tartard', 'Eau', 'Combat', 90, 95, 95, 70, 90, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png', 'Un Pokémon puissant qui sait se défendre et attaquer avec force.'),
(63, 'Abra', 'Psy', NULL, 25, 20, 15, 105, 55, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png', 'Un Pokémon qui utilise la téléportation pour éviter les combats.'),
(64, 'Kadabra', 'Psy', NULL, 40, 35, 30, 120, 70, 105, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png', 'Une évolution d’Abra, il maîtrise des pouvoirs psychiques puissants.'),
(65, 'Alakazam', 'Psy', NULL, 55, 50, 45, 135, 95, 120, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png', 'Une Pokémon très intelligent avec des capacités psychiques extraordinaires.'),
(66, 'Machoc', 'Combat', NULL, 70, 80, 50, 35, 35, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png', 'Un Pokémon musclé qui adore soulever des poids.'),
(67, 'Machopeur', 'Combat', NULL, 80, 100, 70, 50, 60, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png', 'L’évolution de Machoc, il est très fort et peut lancer des attaques puissantes.'),
(68, 'Mackogneur', 'Combat', NULL, 90, 130, 80, 65, 85, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png', 'L’évolution finale de Machoc, connu pour sa force incroyable.'),
(69, 'Chétiflor', 'Plante', 'Poison', 50, 75, 35, 70, 30, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png', 'Un Pokémon plante délicat qui se développe dans les jardins.'),
(70, 'Boustiflor', 'Plante', 'Poison', 65, 90, 50, 85, 45, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png', 'Un Pokémon qui se nourrit de l’énergie solaire pour croître.'),
(71, 'Empiflor', 'Plante', 'Poison', 80, 105, 65, 100, 70, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png', 'Une plante robuste, capable de se défendre avec des toxines.'),
(72, 'Tentacool', 'Eau', 'Poison', 40, 40, 35, 50, 100, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png', 'Un Pokémon de type eau qui se déplace facilement dans l’eau.'),
(73, 'Tentacruel', 'Eau', 'Poison', 80, 70, 65, 80, 120, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png', 'L’évolution de Tentacool, il possède des tentacules venimeux.'),
(74, 'Racaillou', 'Roche', 'Sol', 40, 80, 100, 30, 30, 20, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png', 'Un Pokémon rocheux qui se camoufle dans son environnement.'),
(75, 'Gravalanch', 'Roche', 'Sol', 55, 95, 115, 45, 45, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png', 'Une version plus grande de Racaillou, il est très résistant.'),
(76, 'Grolem', 'Roche', 'Sol', 80, 120, 130, 55, 65, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png', 'Une Pokémon très robuste, capable de lancer des roches avec force.'),
(77, 'Ponyta', 'Feu', NULL, 50, 85, 55, 65, 65, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png', 'Un Pokémon cheval qui court à des vitesses incroyables avec ses flammes.'),
(78, 'Galopa', 'Feu', NULL, 65, 100, 70, 80, 80, 105, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png', 'L’évolution de Ponyta, Galopa est agile et majestueux.'),
(79, 'Ramoloss', 'Eau', 'Psy', 90, 65, 65, 40, 40, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png', 'Un Pokémon qui est souvent endormi et qui se déplace lentement.'),
(80, 'Flagadoss', 'Eau', 'Psy', 95, 75, 110, 100, 80, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png', 'L’évolution de Ramoloss, il utilise ses capacités psychiques pour attaquer.'),
(81, 'Magnéti', 'Electrik', 'Acier', 25, 35, 70, 95, 55, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png', 'Un Pokémon magnétique qui flotte et attire les objets métalliques.'),
(82, 'Magnéton', 'Electrik', 'Acier', 50, 60, 95, 120, 70, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png', 'L’évolution de Magnéti, il est composé de trois Magnétis.'),
(83, 'Canarticho', 'Normal', 'Vol', 52, 90, 55, 58, 62, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png', 'Un Pokémon qui vole à grande vitesse et est connu pour ses attaques.'),
(84, 'Doduo', 'Normal', 'Vol', 35, 85, 45, 35, 35, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png', 'Un Pokémon à deux têtes qui court à grande vitesse.'),
(85, 'Dodrio', 'Normal', 'Vol', 60, 110, 70, 60, 60, 110, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png', 'L’évolution de Doduo, il est rapide et redoutable en combat.'),
(86, 'Otaria', 'Eau', NULL, 65, 45, 55, 45, 70, 45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png', 'Un Pokémon qui aime jouer dans l’eau.'),
(87, 'Lamantine', 'Eau', 'Glace', 90, 70, 80, 70, 95, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png', 'Un Pokémon élégant qui nage lentement dans l’eau froide.'),
(88, 'Tadmorv', 'Poison', NULL, 80, 80, 50, 40, 50, 25, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png', 'Un Pokémon fait de déchets toxiques, il se déplace lentement.'),
(89, 'Grotadmorv', 'Poison', NULL, 105, 105, 75, 65, 100, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png', 'L’évolution de Tadmorv, il est plus grand et plus puissant.'),
(90, 'Kokiyas', 'Eau', 'Glace', 50, 95, 95, 70, 25, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png', 'Un Pokémon qui se cache dans sa coquille pour se protéger.'),
(91, 'Crustabri', 'Eau', 'Glace', 60, 130, 80, 85, 25, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png', 'L’évolution de Kokiyas, il est redoutable en combat.'),
(92, 'Fantominus', 'Spectre', 'Poison', 20, 35, 30, 100, 35, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png', 'Un Pokémon fantomatique qui utilise la peur pour se défendre.'),
(93, 'Spectrum', 'Spectre', 'Poison', 30, 40, 35, 100, 100, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png', 'L’évolution de Fantominus, il est plus puissant et plus agile.'),
(94, 'Ectoplasma', 'Spectre', 'Poison', 60, 65, 60, 120, 70, 110, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 'L’évolution finale de Fantominus, il est connu pour ses puissantes attaques.'),
(95, 'Onix', 'Roche', 'Sol', 35, 45, 160, 30, 45, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png', 'Un Pokémon rocheux qui peut creuser à travers les montagnes.'),
(96, 'Soporifik', 'Psy', NULL, 60, 48, 45, 43, 90, 42, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png', 'Un Pokémon qui utilise ses pouvoirs pour endormir ses ennemis.'),
(97, 'Hypnomade', 'Psy', NULL, 85, 73, 70, 73, 115, 67, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png', 'L’évolution de Soporifik, il peut contrôler les rêves.'),
(98, 'Krabby', 'Eau', NULL, 30, 105, 90, 25, 25, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png', 'Un petit crabe qui se déplace sur la plage.'),
(99, 'Krabboss', 'Eau', NULL, 55, 130, 115, 50, 50, 75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png', 'L’évolution de Krabby, il est plus fort et plus agile.'),
(100, 'Voltorbe', 'Electrik', NULL, 40, 30, 50, 55, 50, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png', 'Un Pokémon en forme de boule qui peut exploser à tout moment.'),
(101, 'Électrode', 'Electrik', NULL, 60, 50, 70, 80, 80, 140, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png', 'L’évolution de Voltorbe, il est connu pour sa vitesse et son explosivité.'),
(102, 'Noeunoeuf', 'Plante', 'Psy', 60, 40, 80, 60, 45, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png', 'Un Pokémon qui se compose de plusieurs œufs, chacun ayant des pouvoirs différents.'),
(103, 'Noadkoko', 'Plante', 'Psy', 95, 95, 80, 70, 70, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png', 'L’évolution de Noeunoeuf, il est grand et majestueux.'),
(104, 'Osselait', 'Normal', NULL, 50, 50, 145, 30, 40, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png', 'Un Pokémon qui se protège avec ses os, il est très résistant.'),
(105, 'Ossatueur', 'Normal', NULL, 75, 80, 200, 60, 50, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png', 'L’évolution d’Osselait, il est connu pour sa défense incroyable.'),
(106, 'Kicklee', 'Combat', NULL, 45, 120, 70, 35, 110, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png', 'Un Pokémon qui se spécialise dans les coups de pied rapides.'),
(107, 'Tygnon', 'Combat', NULL, 50, 100, 60, 60, 85, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png', 'Un Pokémon de combat agile et rapide, expert en esquive.'),
(108, 'Excelangue', 'Normal', NULL, 90, 55, 75, 60, 75, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png', 'Un Pokémon glouton qui adore manger et attraper des proies.'),
(109, 'Smogo', 'Poison', NULL, 40, 65, 95, 60, 45, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', 'Un Pokémon toxique qui se déplace lentement.'),
(110, 'Smogogo', 'Poison', NULL, 65, 90, 120, 85, 70, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png', 'L’évolution de Smogo, il est énorme et très toxique.'),
(111, 'Rhinocorne', 'Sol', 'Roche', 80, 85, 95, 30, 30, 25, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png', 'Un Pokémon robuste avec une grande corne.'),
(112, 'Rhinoféros', 'Sol', 'Roche', 105, 130, 120, 45, 45, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png', 'L’évolution de Rhinocorne, il est encore plus puissant et redouté.'),
(113, 'Leveinard', 'Normal', NULL, 250, 5, 5, 35, 105, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png', 'Un Pokémon très mignon qui est connu pour sa gentillesse.'),
(114, 'Saquedeneu', 'Plante', NULL, 65, 55, 115, 100, 40, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png', 'Un Pokémon qui se déplace lentement, mais qui est très résistant.'),
(115, 'Kangourex', 'Normal', NULL, 105, 95, 80, 40, 80, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png', 'Un Pokémon qui porte son bébé dans sa poche ventrale.'),
(116, 'Hypotrempe', 'Eau', NULL, 30, 40, 70, 70, 25, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png', 'Un Pokémon qui utilise ses pouvoirs pour nager et se déplacer.'),
(117, 'Hypocéan', 'Eau', NULL, 55, 65, 95, 95, 45, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png', 'L’évolution d’Hypotrempe, il est plus puissant et rapide.'),
(118, 'Poissirène', 'Eau', NULL, 45, 67, 60, 35, 50, 63, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png', 'Un Pokémon qui nage dans les rivières et les lacs.'),
(119, 'Poissoroy', 'Eau', NULL, 80, 92, 65, 65, 80, 68, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png', 'L’évolution de Poissirène, il est rapide et redouté dans l’eau.'),
(120, 'Stari', 'Eau', NULL, 30, 45, 55, 70, 55, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png', 'Un petit Pokémon étoile qui nage à la surface de l’eau.'),
(121, 'Staross', 'Eau', 'Psy', 60, 75, 85, 100, 85, 115, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png', 'L’évolution de Stari, il utilise des pouvoirs psychiques en combat.'),
(122, 'M. Mime', 'Psy', 'Fée', 40, 45, 65, 100, 120, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png', 'Un Pokémon qui utilise des illusions pour tromper ses ennemis.'),
(123, 'Insécateur', 'Insecte', 'Vol', 70, 110, 80, 55, 80, 105, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png', 'Un Pokémon insecte rapide et agile, expert en attaque.'),
(124, 'Lippoutou', 'Glace', 'Psy', 65, 50, 35, 115, 95, 95, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png', 'Un Pokémon qui danse et utilise sa magie pour distraire ses ennemis.'),
(125, 'Élektek', 'Electrik', NULL, 65, 83, 57, 95, 85, 105, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png', 'Un Pokémon qui adore courir et générer de l’électricité.'),
(126, 'Magmar', 'Feu', NULL, 65, 95, 57, 100, 85, 93, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png', 'Un Pokémon de feu qui peut cracher des flammes brûlantes.'),
(127, 'Scarabrute', 'Insecte', NULL, 65, 125, 100, 55, 70, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png', 'Un Pokémon puissant qui utilise sa force pour combattre.'),
(128, 'Tauros', 'Normal', NULL, 75, 100, 95, 40, 70, 110, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png', 'Un Pokémon féroce et puissant qui charge à grande vitesse.'),
(129, 'Magicarpe', 'Eau', NULL, 20, 10, 55, 15, 20, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png', 'Un Pokémon inutile qui se débat pour survivre.'),
(130, 'Léviator', 'Eau', 'Vol', 95, 125, 79, 60, 100, 81, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', 'L’évolution de Magicarpe, il est puissant et redouté en combat.'),
(131, 'Lokhlass', 'Eau', 'Glace', 130, 85, 80, 85, 95, 60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png', 'Un Pokémon paisible qui nage lentement dans les eaux froides.'),
(132, 'Métamorph', 'Normal', NULL, 48, 48, 48, 48, 48, 48, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png', 'Un Pokémon capable de se transformer en n’importe quel autre Pokémon.'),
(133, 'Évoli', 'Normal', NULL, 55, 55, 50, 45, 65, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png', 'Un Pokémon qui peut évoluer en plusieurs formes différentes.'),
(134, 'Aquali', 'Eau', NULL, 130, 65, 60, 110, 95, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png', 'L’évolution d’Évoli de type Eau, il est rapide et agile dans l’eau.'),
(135, 'Voltali', 'Électrik', NULL, 65, 65, 60, 110, 95, 130, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png', 'L’évolution d’Évoli de type Électrik, il utilise des attaques rapides.'),
(136, 'Pyroli', 'Feu', NULL, 65, 130, 60, 95, 110, 65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png', 'L’évolution d’Évoli de type Feu, il crache des flammes brûlantes.'),
(137, 'Porygon', 'Normal', NULL, 65, 60, 70, 85, 75, 40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png', 'Un Pokémon numérique qui évolue avec la technologie.'),
(138, 'Amonita', 'Roche', 'Eau', 35, 40, 100, 90, 55, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png', 'Un Pokémon fossile qui nage dans les mers anciennes.'),
(139, 'Amonistar', 'Roche', 'Eau', 70, 60, 125, 115, 70, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png', 'L’évolution d’Amonita, connu pour ses puissantes attaques.'),
(140, 'Kabuto', 'Roche', 'Eau', 30, 80, 90, 55, 45, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png', 'Un Pokémon fossile qui se cache dans sa coquille.'),
(141, 'Kabutops', 'Roche', 'Eau', 60, 115, 105, 65, 70, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png', 'L’évolution de Kabuto, il est connu pour sa vitesse et sa force.'),
(142, 'Ptéra', 'Roche', 'Vol', 80, 105, 65, 60, 75, 130, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png', 'Un Pokémon légendaire capable de voler à grande vitesse.'),
(143, 'Ronflex', 'Normal', NULL, 160, 110, 65, 65, 110, 30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png', 'Un Pokémon énorme qui dort presque toute la journée.'),
(144, 'Artikodin', 'Glace', 'Vol', 90, 85, 100, 95, 125, 85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png', 'Un Pokémon légendaire du froid, connu pour sa puissance.'),
(145, 'Électhor', 'Électrik', 'Vol', 90, 90, 85, 125, 90, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png', 'Un Pokémon légendaire qui contrôle l’électricité et le vent.'),
(146, 'Sulfura', 'Feu', 'Vol', 90, 100, 90, 125, 85, 90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png', 'Un Pokémon légendaire de feu, connu pour sa puissance ardente.'),
(147, 'Minidraco', 'Dragon', NULL, 41, 64, 45, 50, 50, 50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png', 'Un petit Pokémon dragon qui rêve de devenir plus grand.'),
(148, 'Draco', 'Dragon', NULL, 61, 84, 65, 70, 70, 70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png', 'Un Pokémon dragon qui devient plus fort au fil du temps.'),
(149, 'Dracolosse', 'Dragon', 'Vol', 91, 134, 95, 100, 100, 80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', 'L’évolution finale de Minidraco, il est redouté pour sa force.'),
(150, 'Mewtwo', 'Psy', NULL, 106, 110, 90, 154, 90, 130, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png', 'Un Pokémon légendaire créé par des expériences scientifiques, très puissant.'),
(151, 'Mew', 'Psy', NULL, 100, 100, 100, 100, 100, 100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png', 'Un Pokémon légendaire de type Psy, capable d’apprendre toutes les attaques.');


INSERT INTO team (`pokedex_number`, `name`, `type1`, `type2`, `hp`, `attack`, `defense`, `special_attack`, `special_defense`, `speed`, `image_url`, `level`, `description`) VALUES
(23, 'Abo', 'Poison', NULL, 35, 60, 44, 40, 54, 55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png', 8 , 'Un serpent qui se faufile dans l’herbe à la recherche de proies.'),
(109, 'Smogo', 'Poison', NULL, 40, 65, 95, 60, 45, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', 5 ,'Un Pokémon toxique qui se déplace lentement.');